---
neutron:
  source:
    system_dependencies:
      - libmysqlclient-dev 

nova:
  source:
    system_dependencies:   
      - libjs-jquery-tablesorter
      - libmysqlclient-dev
      - python-libvirt
update_ca_certs: update-ca-certificates
